[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
KrylovPreconditioners = "45d422c2-293f-44ce-8315-2cb988662dec"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Ariadne = "0be81120-40bf-4f8b-adf0-26103efb66f1"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SummationByPartsOperators = "9f78cca6-572e-554e-b819-917d2f1cf240"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"

[sources]
Ariadne = {path = ".."}

[compat]
julia = "1.10"
